accounts/urls.py
from django.urls import path
from . import views
 
app_name='accounts'
 
urlpatterns = [
    path('accounts/login/', views.MyLoginView.as_view(), name="login"),
    path('accounts/logout/', views.MyLogoutView.as_view(), name="logout"),
    path('accounts/create/', views.UserCreateView.as_view(),name="create"),
    path('dogs/new/', views.dogNew,name="dogNew"),
    path('dogs/update/<int:pk>/', views.DogUpdate.as_view(),name="dogUpdate"),
    path('dogs/delete/<int:pk>/', views.dogDelete,name="dogDelete"),
    path('dog/show/<int:pk>/', views.dogShow, name='dogShow'),
    path('like/<int:pk>/', views.like, name='like'),
    path('likedperson/', views.likedPerson, name='likedPerson'),
    path('likedopponent/', views.likedOpponent, name='likedOpponent'),
]

myhp/urls.py
from django.urls import path
from . import views
 
app_name='myhp'
 
urlpatterns = [
    path('', views.topPage, name='topPage'),
    path('index/', views.index, name='index'),
    path('fusion/<int:pk>/', views.fusion, name='fusion'),
    path('fusion/<int:pk>/result/', views.result, name='result'),
    path('display/', views.display, name='display'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Dog(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dogname = models.CharField(max_length=100)
    age = models.IntegerField()
    sex = models.CharField(max_length=100)
    introduction = models.CharField(max_length=255)
    image = models.ImageField(upload_to="dogs/")
    like_num = models.IntegerField(default=0)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='like_user')
    dog = models.ForeignKey(Dog, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from .models import Dog

class LoginForm(auth_forms.AuthenticationForm):
    '''ログインフォーム'''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['placeholder'] = field.label

class DogForm(forms.ModelForm):
    class Meta:
        model = Dog
        fields = ('image', 'dogname', 'age', 'sex', 'introduction',)

accounts/views.py
from django.shortcuts import render, loader, redirect
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import TemplateView,CreateView,DeleteView, UpdateView
from django.urls import reverse_lazy, reverse
from . import forms
from .forms import DogForm
from django.http import HttpResponse
from .models import Dog, Like
from django.contrib.auth.models import Group, User
from chats.models import Party
from django.core.paginator import Paginator
from myhp.views import paginate_queryset, is_dog_registed

# Create your views here.

class MyLoginView(LoginView):
    form_class = forms.LoginForm
    template_name = "accounts/login.html"

class MyLogoutView(LoginRequiredMixin, LogoutView):
    template_name = "myhp/topPage.html"

class UserCreateView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/create.html"
    success_url = reverse_lazy("accounts:login")

def dogNew(request):
    if request.method == 'GET':
        form = DogForm()
    else:
        form = DogForm(request.POST, request.FILES)
        form.instance.user_id = request.user.id
        if form.is_valid():
            print('dog_regist is_valid')
            form.save(request.POST)
            return redirect('myhp:index')
        else:
            print('dog_regist false is_valid')
    template = loader.get_template('accounts/dogNew.html')
    context = {
        'form': form,
    }
    return HttpResponse(template.render(context, request))

class DogUpdate(UpdateView):
    template_name = 'accounts/dogNew.html'
    model = Dog
    fields = ['image', 'dogname', 'age', 'sex', 'introduction']
    success_url = reverse_lazy('myhp:index')

def dogDelete(request, pk):
    dog = Dog.objects.get(id=pk)
    dog.delete()
    return redirect('myhp:index')

def dogShow(request, pk):
    dog_flg = is_dog_registed(request)
    dog = Dog.objects.get(id = pk)
    query = Like.objects.filter(user_id=request.user.id, dog_id=pk)
    if query.count() == 0:
        like_flg = 0
    else:
        like_flg = 1
    return render(request, 'accounts/dogShow.html', {
        'dog': dog,
        'dog_flg': dog_flg,
        'like_flg': like_flg,
        })

def like(request, pk):
    query = Like.objects.filter(user_id=request.user.id, dog_id=pk)
    if query.count() == 0:
        # いいねする処理
        likes_tbl = Like()
        likes_tbl.user_id = request.user.id
        likes_tbl.dog_id = pk
        likes_tbl.save()
        dog = Dog.objects.get(id = pk)
        dog.like_num += 1
        dog.save()
        # 相手が自分にいいねしているか確認
        opponent_id = Dog.objects.get(id=pk).user.id
        check = Like.objects.filter(user_id=opponent_id, dog_id=request.user.dog.id)
        if check.count() == query.count():
            try:
                max_id = Party.objects.latest('id').id
            except:
                max_id = 0
            parties_tbl = Party()
            parties_tbl.name = 'group' + str(max_id + 1)
            parties_tbl.save()
            new_party = Party.objects.latest('id')
            new_party.users.add(request.user)
            new_party.users.add(opponent_id)
            return redirect('/chats/index/')
    else:
        # いいね外す処理
        query.delete()
        dog = Dog.objects.get(id = pk)
        dog.like_num -= 1
        dog.save()
    return redirect('/dog/show/' + str(pk))

# いいねした相手
def likedPerson(request):
    headLine = 'じぶんからのいいね！'
    dog_flg = is_dog_registed(request)
    if dog_flg == 1:
        all_objs = Like.objects.filter(user_id=request.user.id).exclude()
        objs = paginate_queryset(request, all_objs, 5)
        # 試行錯誤中
        # test = Party.objects.filter(users=request.user.id)
        # kari = []
        # for t in test:
        #     for i in t.users.all():
        #         if i.id != request.user.id:
        #             kari.append(i.id)
        return render(request, 'accounts/liked_person.html', {
            'dog_flg': dog_flg,
            'objs': objs,
            'headLine': headLine,
        })
    else:
        return render(request, 'accounts/liked_person.html', {
            'dog_flg': dog_flg,
            'headLine': headLine,
        })

# いいねされた相手
def likedOpponent(request):
    headLine = 'あいてからのいいね！'
    dog_flg = is_dog_registed(request)
    if dog_flg == 1:
        all_objs = Like.objects.filter(dog_id=request.user.dog.id)
        objs = paginate_queryset(request, all_objs, 5)
        return render(request, 'accounts/liked_opponent.html', {
            'dog_flg': dog_flg,
            'objs': objs,
            'headLine': headLine,
        })
    else:
        return render(request, 'accounts/liked_opponent.html', {
            'dog_flg': dog_flg,
            'headLine': headLine,
        })

templates/accounts/create.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="container" style="margin-top: 200px;">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Sign Up</h3>
                <div class="d-flex justify-content-end social_icon">
                    <span><i class="fab fa-facebook-square"></i></span>
                    <span><i class="fab fa-google-plus-square"></i></span>
                    <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    <label class="memberLabel">username</label>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <label class="memberLabel">password</label>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password1 }}
                    </div>
                    <label class="memberLabel">password(one more)</label>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password2 }}
                    </div>
                    <!-- <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div> -->
                    <div class="form-group">
                        <input type="submit" value="Sign Up" class="btn float-right login_btn">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Do you have an account?<a href="{% url 'accounts:login' %}">Sign In</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts/dogNew.html
{% extends '../shared/base.html' %}
{% block content %}

<div class="dogNewWrap col-lg-3 mx-auto text-center">
  <div class="dog-registration">
    <form id="new_dog" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group-img">
        <label class="DogLabel">image</label>
        <div class="userImgPreview" id="userImgPreview">
          <img id="thumbnail" class="userImgPreview_content" accept="image/*" src="">
        </div>
        {{ form.image }}
      </div>
      <div class="form-group">
        <label class="newDogLabel">dogname</label>
        {{ form.dogname }}
      </div>
      <div class="form-group">
        <label class="newDogLabel">age</label>
        {{ form.age }}
      </div>
      <div class="form-group">
        <label class="newDogLabel">sex</label>
        {{ form.sex }}
      </div>
      <div class="form-group">
        <label class="newDogLabel">introduction</label>
        {{ form.introduction }}
      </div>
      <button type="submit" class="dogBtn">登録する</button>
    </form>
  </div>
</div>

{% endblock content %}

templates/accounts/dogShow.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">{{dog.user.username}}さん</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="dogShowWrap w-100 p-5">
    <div class="dogShowBox mx-auto h-100 w-75 d-flex p-3">
      <div class="dogShowLeft mr-3 text-center">
        <img class="dogShowImage" src="{{ dog.image.url }}">
        <div class="dogShowNav w-100 p-3 my-3">
          <i class="fas fa-thumbs-up"></i>&emsp;{{dog.like_num}}&emsp;いいね！
        </div>
        {% if like_flg == 0 %}
        <a href="{% url 'accounts:like' pk=dog.id %}"
          class="mx-auto w-75 d-block btn btn-warning rounded-pill align-middle mb-3">いいねボタン</a>
        {% else %}
        <a href="{% url 'accounts:like' pk=dog.id %}"
          class="mx-auto w-75 d-block btn btn-danger rounded-pill align-middle mb-3">いいねを外す</a>
        {% endif %}
        <a href="{% url 'myhp:fusion' pk=dog.id %}"
          class="mx-auto w-75 d-block btn btn-info rounded-pill align-middle">合成ボタン</a>
      </div>
      <div class="dogShowNav p-3">
        飼い主：{{dog.user.username}}<br>
        名前：{{dog.dogname}}<br>
        年齢：{{dog.age}}<br>
        性別：{{dog.sex}}<br>
        紹介文：{{dog.introduction}}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/accounts/like.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">{{headLine}}</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="wrapRight col-lg-9 pt-4">
    <div class="likeWrap">
      {% block like %}
      <!-- like -->
      {% endblock %}
    </div>
    {% include "../shared/pagination.html" %}
  </div>
</div>
{% endblock content %}

templates/accounts/liked_opponent.html
{% extends './like.html' %}
{% block like %}
{% for obj in objs %}
<div class="likeBox mx-auto col-9 my-5 p-0">
  <a href="{% url 'accounts:dogShow' pk=obj.user.dog.id %}" class="likeLink d-flex">
    <img class="likeImage" src="{{ obj.user.dog.image.url }}">
    <div class="p-4">
      {{obj.user.username}}さん<br>
      なまえ：{{obj.user.dog.dogname}}<br>
      {{obj.user.dog.age}}さい<br>
      性別：{{obj.user.dog.sex}}<br>
      紹介文：{{obj.user.dog.introduction}}<br>
    </div>
  </a>
  <div class="text-center py-3">
    <a href="#" class="btn btn-outline-warning rounded-pill align-middle">いいねありがとうボタン</a>
  </div>
</div>
{% endfor %}

{% endblock like %}

templates/accounts/liked_person.html
{% extends './like.html' %}
{% block like %}
{% for obj in objs %}
<div class="likeBox mx-auto col-9 my-5 p-0">
  <a href="{% url 'accounts:dogShow' pk=obj.dog.id %}" class="likeLink d-flex">
    <img class="likeImage" src="{{ obj.dog.image.url }}">
    <div class="p-4">
      {{obj.dog.user.username}}さん<br>
      なまえ：{{obj.dog.dogname}}<br>
      {{obj.dog.age}}さい<br>
      性別：{{obj.dog.sex}}<br>
      紹介文：{{obj.dog.introduction}}<br>
    </div>
  </a>
</div>
{% endfor %}
{% endblock like %}

templates/accounts/login.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="container" style="margin-top: 200px;">
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <h3>Sign In</h3>
                <div class="d-flex justify-content-end social_icon">
                    <span><i class="fab fa-facebook-square"></i></span>
                    <span><i class="fab fa-google-plus-square"></i></span>
                    <span><i class="fab fa-twitter-square"></i></span>
                </div>
            </div>
            <div class="card-body">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        {{ form.username }}
                    </div>
                    <div class="input-group form-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        {{ form.password }}
                    </div>
                    <!-- <div class="row align-items-center remember">
                        <input type="checkbox">Remember Me
                    </div> -->
                    <div class="form-group">
                        <input type="submit" value="Login" class="btn float-right login_btn">
                    </div>
                </form>
            </div>
            <div class="card-footer">
                <div class="d-flex justify-content-center links">
                    Don't have an account?<a href="{% url 'accounts:create' %}">Sign Up</a>
                </div>
                <div class="d-flex justify-content-center">
                    <a href="#">Forgot your password?</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}