accounts/urls.py
from django.urls import path
from . import views
 
app_name='accounts'
 
urlpatterns = [
    path('accounts/login/', views.MyLoginView.as_view(), name="login"),
    path('accounts/logout/', views.MyLogoutView.as_view(), name="logout"),
    path('accounts/create/', views.UserCreateView.as_view(),name="create"),
    path('dogs/new/', views.dogNew,name="dogNew"),
    path('dogs/update/<int:pk>/', views.DogUpdate.as_view(),name="dogUpdate"),
    path('dogs/delete/<int:pk>/', views.dogDelete,name="dogDelete"),
    path('dog/show/<int:pk>/', views.dogShow, name='dogShow'),
    path('like/<int:pk>/', views.like, name='like'),
    path('likedperson/', views.likedPerson, name='likedPerson'),
    path('likedopponent/', views.likedOpponent, name='likedOpponent'),
]

myhp/urls.py
from django.urls import path
from . import views
 
app_name='myhp'
 
urlpatterns = [
    path('', views.topPage, name='topPage'),
    path('index/', views.index, name='index'),
    path('fusion/<int:pk>/', views.fusion, name='fusion'),
    path('fusion/<int:pk>/result/', views.result, name='result'),
    path('display/', views.display, name='display'),
]

myhp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Document(models.Model):
    users = models.ManyToManyField(User, verbose_name='ユーザー')
    first_image = models.ImageField(upload_to='results/', default='defo')
    second_image = models.ImageField(upload_to='results/', default='defo')
    uploaded_at = models.DateTimeField(auto_now_add=True)

myhp/views.py
from django.shortcuts import render, redirect
from accounts.models import Dog
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Document
from PIL import Image
import cv2
from django.conf import settings

# Create your views here.

def topPage(request):
    if request.user.is_authenticated:
        return redirect('myhp:index')
    else:
        objs = Dog.objects.order_by('-id')[:5]
        return render(request, 'myhp/topPage.html', {
            'objs': objs,
        })

def index(request):
    try:
        all_objs = Dog.objects.order_by('-id').exclude(user_id=request.user.id)
    except:
        all_objs = Dog.objects.order_by('-id')
    objs = paginate_queryset(request, all_objs, 12)
    dog_flg = is_dog_registed(request)
    return render(request, 'myhp/index.html', {
        'objs': objs,
        'dog_flg': dog_flg,
    })

def fusion(request, pk):
    opponent = Dog.objects.get(id = pk)
    return render(request, 'myhp/fusion.html', {
        'opponent': opponent,
    })

def result(request, pk):
    headLine = '結果'
    myself = Dog.objects.get(user_id = request.user.id)
    opponent = Dog.objects.get(id = pk)

    try:
        max_id = Document.objects.latest('id').id
    except:
        max_id = 0
    docment_tbl = Document()
    docment_tbl.first_image = "results/output" + str(max_id + 1) + ".jpg"
    docment_tbl.second_image = "results/output_two" + str(max_id + 1) + ".jpg"
    docment_tbl.save()
    new_document = Document.objects.latest('id')
    new_document.users.add(request.user)
    new_document.users.add(opponent.user.id)

    input_path = settings.BASE_DIR + myself.image.url
    input_path_two = settings.BASE_DIR + opponent.image.url
    output_path = settings.BASE_DIR + "/media/results/output" + str(max_id + 1) + ".jpg"
    output_path_two = settings.BASE_DIR + "/media/results/output_two" + str(max_id + 1) + ".jpg"
    src = cv2.imread(input_path)
    src_two = cv2.imread(input_path_two)
    img = src.copy()
    img_two = src_two.copy()
    def face_swap(src, src_two, x, y, width, height, ratio=1):
        dst = src.copy()
        dst_02 = src_two.copy()
        dst[y:y + height, x:x + width] = dst_02[y:y + height, x:x + width]
        return dst
    face_cascade_path = './haarcascade_frontalcatface.xml'
    face_cascade = cv2.CascadeClassifier(face_cascade_path)
    face_cascade_two = cv2.CascadeClassifier(face_cascade_path)
    src_gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
    img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    src_two_gray = cv2.cvtColor(src_two, cv2.COLOR_BGR2GRAY)
    img_two_gray = cv2.cvtColor(img_two, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(src_gray)
    faces_two = face_cascade_two.detectMultiScale(img_two_gray)
    for x, y, w, h in faces:
        for a, b, c, d in faces_two:
            dst_face_01 = face_swap(src, src_two, x, y, w, h)
            dst_face_02 = face_swap(img_two, img, a, b, c, d)
    
            cv2.imwrite(output_path, dst_face_01)
            cv2.imwrite(output_path_two, dst_face_02)

    return render(request, 'myhp/result.html', {
        'opponent': opponent,
        'new_document': new_document,
        'headLine': headLine,
    })

def display(request):
    dog_flg = is_dog_registed(request)
    all_objs = Document.objects.order_by('-id')
    objs = paginate_queryset(request, all_objs, 10)
    return render(request, 'myhp/display.html', {
        'dog_flg': dog_flg,
        'objs': objs,
    })

def paginate_queryset(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        objs = paginator.page(page)
    except PageNotAnInteger:
        objs = paginator.page(1)
    except EmptyPage:
        objs = paginator.page(paginator.num_pages)
    return objs

def is_dog_registed(request):
    dog = Dog.objects.filter(user_id=request.user.id)
    if dog.count() == 0:
        dog_flg = 0
    else:
        dog_flg = 1
    return dog_flg

templates/myhp/display.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">合成一覧</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="displayRight w-100">
    <div class="displayWrap">
      {% for obj in objs %}
      <div class="displayBox text-center p-2 my-1 w-75 mx-auto">
        <img class="displayImage" src="{{ obj.first_image.url }}">
        <img class="displayImage" src="{{ obj.second_image.url }}">
        &emsp;&emsp;
        {% for o in obj.users.all %}
        <a href="{% url 'accounts:dogShow' pk=o.dog.id %}" class="displayLink">
          <img class="displayUserImage" src="{{ o.dog.image.url }}">
          {{ o }}さん
        </a>
        {% endfor %}
      </div>
      {% endfor %}
    </div>
    {% include "../shared/pagination.html" %}
  </div>
</div>

{% endblock content %}

templates/myhp/fusion.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">合成画面</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="fusionWrap w-100 d-flex align-items-center">
    <div class="w-75 mx-auto text-center">
      {% block fusion %}
      <div class="fusionBox mb-5">
        <img class="fusionDogImage" src="{{ user.dog.image.url }}">
        &emsp;&emsp;&emsp;&emsp;&emsp;
        <img class="fusionDogImage" src="{{ opponent.image.url }}">
      </div>
      <a href="{% url 'myhp:result' pk=opponent.id %}" class="btn btn-outline-info rounded-pill align-middle">合成する</a>
      {% endblock %}
    </div>
  </div>
</div>
{% endblock content %}

templates/myhp/fusionBase.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="myhpWrap">
  {% include "./sideBar.html" %}
  <div class="fusionWrap">
    <div class="headLine">
      {{headLine}}
    </div>
    <div class="fusionBox">
      <img class="fusionDogImage" src="{{ user.dog.image.url }}">　　　
      <img class="fusionDogImage" src="{{ opponent.image.url }}">
    </div>
    {% block fusion %}
    <!-- content -->
    {% endblock %}
  </div>
</div>
{% endblock content %}

templates/myhp/index.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">ユーザー一覧</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% if user.is_authenticated %}
  {% include "../shared/sideBar.html" %}
  <div class="wrapRight col-lg-9 pt-4">
    <div class="indexRightBox py-5">
      {% for obj in objs %}
      <a href="{% url 'accounts:dogShow' pk=obj.id %}" class="userBox col-lg-3 text-center d-block">
        <img class="userImage" src="{{ obj.image.url }}">
        <div>なまえ：{{ obj.dogname }}</div>
        <div>{{ obj.sex }}&emsp;&emsp;&emsp;{{ obj.age }}さい</div>
      </a>
      {% endfor %}
    </div>
    {% include "../shared/pagination.html" %}
  </div>
  {% else %}
  <div class="wrapRight mx-auto col-lg-9 pt-4">
    <div class="headLine w-25 mx-auto text-center">
      {{headLine}}
    </div>
    <div class="indexRightBox py-5">
      {% for obj in objs %}
      <a href="{% url 'accounts:dogShow' pk=obj.id %}" class="userBox col-lg-3 text-center d-block">
        <img class="userImage" src="{{ obj.image.url }}">
        <div>なまえ：{{ obj.dogname }}</div>
        <div>{{ obj.sex }}&emsp;&emsp;&emsp;{{ obj.age }}さい</div>
      </a>
      {% endfor %}
    </div>
    {% include "../shared/pagination.html" %}
  </div>
  {% endif %}
</div>
{% include "../shared/footer.html" %}
{% endblock content %}

templates/myhp/result.html
{% extends './fusion.html' %}
{% block fusion %}
<div class="fusionBox mb-5">
  <img class="fusionResultImage" src="{{ user.dog.image.url }}">
  <p class="d-inline">さんと</p>
  &emsp;
  <img class="fusionResultImage" src="{{ opponent.image.url }}">
  <p class="d-inline">さんを合成すると</p>
</div>
<div class="fusionBox">
  <img class="fusionDogImage" src="{{ new_document.first_image.url }}">
  &emsp;&emsp;&emsp;&emsp;&emsp;
  <img class="fusionDogImage" src="{{ new_document.second_image.url }}">
</div>
あいてにいいね！
{% endblock fusion %}

templates/myhp/topPage.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="mx-auto w-75 px-5">
  <div class="topImageWrap mb-3">
    <div class="topImageMessage h-100 p-5">
      <div class="h-75 d-flex align-items-center justify-content-center">
        D.matchAppはわんちゃんのための<br>マッチングアプリです。<br>
        子犬は両親の血統によって<br>様々な容姿の子が生まれます。<br>
        マッチング前にイメージを確認して<br>わんちゃんに理想のお相手を<br>見つけてあげましょう。
      </div>
      <div class="text-center">
        <a class="btn btn-outline-primary rounded-pill align-middle mt-5" href="{% url 'accounts:login' %}">ログインする</a>
      </div>
    </div>
  </div>

  <div class="topHowToUseWrap mb-3 py-5">
    <ul class="topHowToUseBox d-flex justify-content-center">
      <li class="topHowToUse col-lg-2 p-0">
        <img class="topHowToUsePhoto" src="/static/images/howto1.png">
        <div class="topHowToUsetext p-2">
          <div class="topHowToUseNo">1</div>
          <p class="topHowToUseHeadline">
            <br>理想の相手を探しましょう</p>
          <p>わんちゃんに理想のお相手を探してあげましょう。</p>
        </div>
      </li>
      <li class="topHowToUse col-lg-2 p-0">
        <img class="topHowToUsePhoto" src="/static/images/howto2.png">
        <div class="topHowToUsetext p-2">
          <div class="topHowToUseNo">2</div>
          <p class="topHowToUseHeadline">
            子犬の容姿を<br>みてみましょう</p>
          <p>わんちゃんの写真を元に子犬のイメージを作成します。</p>
        </div>
      </li>
      <li class="topHowToUse col-lg-2 p-0">
        <img class="topHowToUsePhoto" src="/static/images/howto3.png">
        <div class="topHowToUsetext p-2">
          <div class="topHowToUseNo">3</div>
          <p class="topHowToUseHeadline">
            気に入ったお相手に<br>いいねを送りましょう</p>
          <p>気になるお相手を見つけたら「いいね」を送りましょう。</p>
        </div>
      </li>
      <li class="topHowToUse col-lg-2 p-0">
        <img class="topHowToUsePhoto" src="/static/images/howto4.png">
        <div class="topHowToUsetext p-2">
          <div class="topHowToUseNo">4</div>
          <p class="topHowToUseHeadline">
            マッチングしたら<br>メッセージを送りましょう</p>
          <p>お互いがいいねを押したらメッセージの交換ができる様になります。</p>
        </div>
      </li>
    </ul>
  </div>

  <div class="toppageUserWrap text-center py-5">
    <div class="toppage-user-head">新着のお相手</div>
    <ul class="list-group list-group-horizontal justify-content-center my-3">
      {% for dog in objs %}
      <li class="toppage-user list-group-item col-lg-2 mx-1">
        <a href="#" class="toppage-user-link d-block">
          <img class="toppageUserPhoto" src="{{ dog.image.url }}">
          <p class="">なまえ：{{ dog.dogname }}<br>
            {{ dog.sex }}&emsp;&emsp;
            {{ dog.age }}さい
          </p>
        </a>
      </li>
      {% endfor %}
    </ul>
    <div class="text-right pr-5">
      <a href="{% url 'myhp:index' %}">もっと見る>>
    </div>
  </div>
</div>
{% include "../shared/footer.html" %}
{% endblock content %}