chats/urls.py
from django.urls import path
from . import views
 
app_name='chats'
 
urlpatterns = [
    path('chats/index/', views.index, name="index"),
    path('chats/show/<int:id>', views.show, name='show'),
]

myhp/urls.py
from django.urls import path
from . import views
 
app_name='myhp'
 
urlpatterns = [
    path('', views.topPage, name='topPage'),
    path('index/', views.index, name='index'),
    path('fusion/<int:pk>/', views.fusion, name='fusion'),
    path('fusion/<int:pk>/result/', views.result, name='result'),
    path('display/', views.display, name='display'),
]

chats/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Party(models.Model):
    users = models.ManyToManyField(User, verbose_name='ユーザー')
    name = models.CharField(max_length=20)

class Chat(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    party = models.ForeignKey(Party, on_delete=models.CASCADE)
    text = models.CharField(max_length=150)
    uploaded_at = models.DateTimeField(auto_now_add=True)

chats/forms.py
from django.contrib.auth import forms as auth_forms
from django import forms
from .models import Chat

class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ('text',)

chats/views.py
from django.shortcuts import render, loader, redirect
from django.http import HttpResponse
from chats.models import Party, Chat
from .forms import ChatForm
from django.http import JsonResponse
from myhp.views import is_dog_registed

# Create your views here.

def index(request):
    dog_flg = is_dog_registed(request)
    parties = Party.objects.filter(users=request.user.id)
    return render(request, 'chats/index.html', {
        'parties' : parties,
        'dog_flg' : dog_flg
        })

def show(request, id):
    if request.method == 'GET':
        form = ChatForm()
    else:
        form = ChatForm(request.POST, request.FILES)
        form.instance.user_id = request.user.id
        form.instance.party_id = id
        if form.is_valid():
            print('chat_regist is_valid')
            form.save(request.POST)
            return redirect('/chats/show/' + str(id))
        else:
            print('chat_regist false is_valid')

    parties = Party.objects.filter(users=request.user.id)
    chats = Chat.objects.filter(party_id=id)
    template = loader.get_template('chats/show.html')
    context = {
        'form': form,
        'chats' : chats,
        'parties' : parties,
    }
    return HttpResponse(template.render(context, request))

def ajax_post_add(request):
    title = request.POST.get('text')
    post = Chat.objects.create(text=title)
    d = {
        'title': post.text,
    }
    return JsonResponse(d)

templates/chats/index.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item active" aria-current="page">メッセージ</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="chatWrap col-lg-9 d-flex p-0">
    <div class=" cahtMembers col-lg-5">
      {% for party in parties %}
      {{party.chat}}
      <a href="{% url 'chats:show' id=party.id %}" class="chatLink d-flex align-items-center my-2 p-2">
        {% for p in party.users.all %}
        {% if p.id != request.user.id %}
        <img class="chatUserImage" src="{{ p.dog.image.url }}">
        <p class="mb-0">{{p}}</p>
        {% endif %}
        {% endfor %}
      </a>
      {% endfor%}
    </div>
    <div class="chatRight col-lg-7 p-0">
      <div class="h-100 d-flex align-items-center justify-content-center">
        <div>
          <img class="chatLogo w-25 mx-auto d-block" src="/static/images/mark.png">
          <img class="chatLogo w-100" src="/static/images/logo.png">
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/chats/show.html
{% extends '../shared/base.html' %}
{% block content %}
<div class="breadcrumbWrap mx-auto w-75 px-5">
  <nav aria-label="パンくずリスト">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'myhp:topPage' %}"><i class="fa fa-home">ホーム</i></a></li>
      <li class="breadcrumb-item"><a href="{% url 'chats:index' %}">メッセージ一覧</a></li>
      <li class="breadcrumb-item active" aria-current="page">個別メッセージ</li>
    </ol>
  </nav>
</div>
<div class="mx-auto w-75 d-flex px-5">
  {% include "../shared/sideBar.html" %}
  <div class="chatWrap col-lg-9 d-flex p-0">
    <div class=" cahtMembers col-lg-5">
      {% for party in parties %}
      {{party.chat}}
      <a href="{% url 'chats:show' id=party.id %}" class="chatLink d-flex align-items-center my-2 p-2">
        {% for p in party.users.all %}
        {% if p.id != request.user.id %}
        <img class="chatUserImage" src="{{ p.dog.image.url }}">
        <p class="mb-0">{{p}}</p>
        {% endif %}
        {% endfor %}
      </a>
      {% endfor%}
    </div>
    <div class="chatRight col-lg-7 p-0">
      <div class="chatMessageWrap p-4">
        {% for chat in chats %}
        {% if chat.user.id == request.user.id %}
        <div class="clearfix">
          <div class="myComment float-right d-flex">
            <!-- <a href="#" class="commentDeleteIcon">
                  <i class="fas fa-trash-alt" style="font-size: 9px;"></i>
                </a> -->
            <p class="myCommentText">
              {{ chat.text}}
            </p>
            <div class="commentUser text-center">
              <img class="commentUserImage" src="{{ chat.user.dog.image.url }}">
              <p>{{ chat.user.username }}</p>
            </div>
          </div>
        </div>
        {% else %}
        <div class="theirComment d-flex">
          <div class="theircommentUser text-center mr-3">
            <img class="commentUserImage" src="{{ chat.user.dog.image.url }}">
            <p>{{ chat.user.username }}</p>
          </div>
          <p class="theirCommentText">
            {{ chat.text}}
          </p>
        </div>
        {% endif %}
        {% endfor%}
      </div>
      <div class="chatMessageForm w-100">
        <form id="new_message" action="" method="POST">
          {% csrf_token %}
          <textarea name="text" id="id_text" placeholder="メッセージを入力"></textarea>
          <button type="submit" class="chatBtn">
            <i class="fas fa-paper-plane"></i>
          </button>
        </form>
      </div>

    </div>
  </div>
</div>
{% endblock content %}