accounts/urls.py
from django.urls import path
from . import views
 
app_name='accounts'
 
urlpatterns = [
    path('accounts/login/', views.MyLoginView.as_view(), name="login"),
    path('accounts/logout/', views.MyLogoutView.as_view(), name="logout"),
    path('accounts/create/', views.UserCreateView.as_view(),name="create"),
    path('dogs/new/', views.dogNew,name="dogNew"),
    path('dogs/update/<int:pk>/', views.DogUpdate.as_view(),name="dogUpdate"),
    path('dogs/delete/<int:pk>/', views.dogDelete,name="dogDelete"),
    path('dog/show/<int:pk>/', views.dogShow, name='dogShow'),
    path('like/<int:pk>/', views.like, name='like'),
    path('likedperson/', views.likedPerson, name='likedPerson'),
    path('likedopponent/', views.likedOpponent, name='likedOpponent'),
]

chats/urls.py
from django.urls import path
from . import views
 
app_name='chats'
 
urlpatterns = [
    path('chats/index/', views.index, name="index"),
    path('chats/show/<int:id>', views.show, name='show'),
]

myhp/urls.py
from django.urls import path
from . import views
 
app_name='myhp'
 
urlpatterns = [
    path('', views.topPage, name='topPage'),
    path('index/', views.index, name='index'),
    path('fusion/<int:pk>/', views.fusion, name='fusion'),
    path('fusion/<int:pk>/result/', views.result, name='result'),
    path('display/', views.display, name='display'),
]

templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% load bootstrap4 %}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css"
    integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <script src="{% static 'js/preview.js' %}"></script>
  <script src="{% static 'js/fadein.js' %}"></script>
  <title>D.matchApp</title>
</head>

<body>
  <div class="header container-fluid d-flex justify-content-between align-items-center fixed-top px-5">
    <a href="{% url 'myhp:topPage' %}" class="headerLogo d-block h-100"></a>
    {% if user.is_authenticated %}
    <a class="btn btn-outline-primary rounded-pill h-50 align-middle mx-3" href="{% url 'accounts:logout' %}">ログアウト</a>
    {% else %}
    <div class="row">
      <a class="btn btn-outline-primary rounded-pill h-50 align-middle mx-3" href="{% url 'accounts:create' %}">新規登録</a>
      <a class="btn btn-outline-primary rounded-pill h-50 align-middle mx-3" href="{% url 'accounts:login' %}">ログインする</a>
    </div>
    {% endif %}
  </div>
    {% block content %}
    <!-- content -->
    {% endblock %}
</body>

</html>

templates/shared/footer.html
<div class="footer mt-3"></div>

templates/shared/pagination.html
<ul class="pagination justify-content-center" style="height: 40px;">
  <!-- 前へ の部分 -->
  {% if objs.has_previous %}
  <li class="page-item">
    <a class="page-link" href="?page={{ objs.previous_page_number }}">
      <span aria-hidden="true">&laquo;</span>
    </a>
  </li>
  {% endif %}

  <!-- 数字の部分 -->
  {% for num in objs.paginator.page_range %}
  {% if objs.number == num %}
  <li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
  {% else %}
  <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
  {% endif %}
  {% endfor %}

  <!-- 次へ の部分 -->
  {% if objs.has_next %}
  <li class="page-item">
    <a class="page-link" href="?page={{ objs.next_page_number }}">
      <span aria-hidden="true">&raquo;</span>
    </a>
  </li>
  {% endif %}
</ul>

templates/shared/sideBar.html
<div class="col-lg-3">
  <div class="sideBarNavBox text-center my-1">
    <p class="sideBarUserName">{{user.username}}さん</p>
    {% if dog_flg == 0 %}
    <a href="{% url 'accounts:dogNew' %}" class="sideBarLink">
      <i class="fas fa-paw"></i>
      犬を登録してください
    </a>
    {% else %}
    <a href="{% url 'accounts:dogShow' pk=user.dog.id %}" class="sideBarLink">
      <img class="sideBarDogImage" src="{{ user.dog.image.url }}">
      <div>なまえ：{{ user.dog.dogname }}</div>
      <div>{{ user.dog.sex }}&emsp;&emsp;&emsp;{{ user.dog.age }}さい</div>
    </a>
    <div class="sideBarNavBox text-center pb-3">
      <a href="{% url 'accounts:dogUpdate' pk=user.dog.id %}" class="sideBarLink mx-2"><i class="fas fa-edit"></i>編集する</a>
      <a href="{% url 'accounts:dogDelete' pk=user.dog.id %}" class="sideBarLink mx-2"><i class="fas fa-trash-alt"></i>削除する</a>
    </div>
    {% endif %}
  </div>
  <div class="sideBarNavBox text-center my-1 py-3">
    <div class="text-left pl-5"><i class="fas fa-thumbs-up"></i>いいね！</div>
    <a href="{% url 'accounts:likedOpponent' %}" class="sideBarLink d-block py-2">あいてからのいいね！</a>
    <a href="{% url 'accounts:likedPerson' %}" class="sideBarLink d-block py-2">じぶんからのいいね！</a>
  </div>
  <div class="sideBarNavBox text-center my-1 py-3">
    <div class="text-left pl-5"><i class="fas fa-comments"></i>マッチング</div>
    <a href="{% url 'chats:index' %}" class="sideBarLink d-block py-2">メッセージ</a>
  </div>
  <div class="sideBarNavBox text-center my-1 py-3">
    <div class="text-left pl-5">合成</div>
    <a href="{% url 'myhp:display' %}" class="sideBarLink d-block py-2">合成写真の一覧</a>
  </div>
</div>